os: linux

hooks:
  ApplicationStart:
    - location: deploy_hooks/install-nginx.sh
      timeout: 1800
      runas: root
  ValidateService:
    - location: deploy_hooks/verify-deployment.sh
      runas: root