os: linux

files:
  - source: aws/codedeploy/install_nginx.sh
    destination: /tmp/aftp/install_nginx.sh

permissions:
  - object: /tmp/aftp/
    pattern: "*.sh
    mode: 755
    type:
      - file

hooks:
   BeforeInstall:
     - location: /tmp/aftp/install_nginx.sh
       timeout: 180

