os: linux
version: 0.0

files:
  - source: app
    destination: /opt/aftp/app

hooks:
  ApplicationStart:
    - location: aws/deploy-hooks/install-nginx.sh
      timeout: 1800
      runas: root
  ValidateService:
    - location: aws/deploy-hooks/verify-deployment.sh
      runas: root